#!/bin/bash
#
# Start lsyncd for LOF Audio File Sync
#

PLUGIN_DIR="/opt/fpp/plugins/lof-audio-sync"
CONFIG_FILE="$PLUGIN_DIR/config.json"
LSYNCD_CONFIG="/etc/lsyncd/lsyncd-lof.conf.lua"

# Read configuration
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Configuration file not found"
    exit 1
fi

ENABLED=$(jq -r '.enabled' "$CONFIG_FILE")
if [ "$ENABLED" != "true" ]; then
    echo "Sync is disabled in configuration"
    exit 0
fi

DEST_HOST=$(jq -r '.destination_host' "$CONFIG_FILE")
DEST_PATH=$(jq -r '.destination_path' "$CONFIG_FILE")
SSH_USER=$(jq -r '.ssh_user' "$CONFIG_FILE")
SYNC_DELAY=$(jq -r '.sync_delay' "$CONFIG_FILE")
SOURCE_PATH=$(jq -r '.source_path' "$CONFIG_FILE")

if [ -z "$DEST_HOST" ]; then
    echo "Destination host not configured"
    exit 1
fi

# Create lsyncd configuration
cat > "$LSYNCD_CONFIG" <<EOF
-- LOF Audio File Sync Configuration
-- Auto-generated by plugin

settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status",
    statusInterval = 5,
    nodaemon = false
}

sync {
    default.rsync,
    source = "$SOURCE_PATH",
    target = "${SSH_USER}@${DEST_HOST}:${DEST_PATH}",
    delay = $SYNC_DELAY,
    rsync = {
        archive = true,
        compress = true,
        verbose = true,
        _extra = {"--delete"}
    }
}
EOF

# Stop any existing lsyncd
systemctl stop lsyncd 2>/dev/null || true

# Start lsyncd with our configuration
systemctl start lsyncd

# Enable on boot
systemctl enable lsyncd

echo "lsyncd started successfully"
