#!/bin/bash
#
# Start lsyncd for LOF Audio File Sync
#

PLUGIN_DIR="/opt/fpp/plugins/fpp-lof-audio-sync"
SETTINGS_FILE="$PLUGIN_DIR/settings.json"
LSYNCD_CONFIG="/etc/lsyncd/lsyncd-lof.conf.lua"

# Check if settings file exists
if [ ! -f "$SETTINGS_FILE" ]; then
    echo "Settings file not found"
    exit 1
fi

# Read settings
ENABLED=$(jq -r '.enabled' "$SETTINGS_FILE")
if [ "$ENABLED" != "true" ]; then
    echo "Sync is disabled"
    systemctl stop lsyncd 2>/dev/null
    exit 0
fi

DEST_HOST=$(jq -r '.destination_host' "$SETTINGS_FILE")
DEST_PATH=$(jq -r '.destination_path' "$SETTINGS_FILE")
SSH_USER=$(jq -r '.ssh_user' "$SETTINGS_FILE")
SYNC_DELAY=$(jq -r '.sync_delay' "$SETTINGS_FILE")
SOURCE_PATH=$(jq -r '.source_path' "$SETTINGS_FILE")

# Validate settings
if [ -z "$DEST_HOST" ] || [ "$DEST_HOST" = "null" ]; then
    echo "Destination host not configured"
    exit 1
fi

# Create lsyncd configuration
cat > "$LSYNCD_CONFIG" <<EOF
-- LOF Audio File Sync Configuration
-- Auto-generated by FPP plugin

settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status",
    statusInterval = 5
}

sync {
    default.rsync,
    source = "$SOURCE_PATH",
    target = "${SSH_USER}@${DEST_HOST}:${DEST_PATH}",
    delay = $SYNC_DELAY,
    rsync = {
        archive = true,
        compress = true,
        verbose = true,
        perms = false,
        owner = false,
        group = false,
        _extra = {"--delete", "--no-perms", "--no-owner", "--no-group", "--omit-dir-times"}
    }
}
EOF

# Stop any existing lsyncd
systemctl stop lsyncd 2>/dev/null || true

# Start lsyncd with our configuration
lsyncd "$LSYNCD_CONFIG"

# Enable on boot
systemctl enable lsyncd 2>/dev/null || true

echo "lsyncd started successfully"
